# Generated by Django 5.0.7 on 2024-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_topic_answers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
